public Class A0

{

public Account createAccount(String name)  //method to create account

{//comment source line4 srcmodififylast

Account QD123456789012356780Tes00t= new Account();

Account a012311111123312= new Account();

Account a01231111112= new Account();

Account a0123111111= new Account(); //commentsource line2 modify1

a0123111111.Name = name; //line3

return a0123111111; //line7 src modifylast1

//a2111111111111111111111111

//007111111111

//vcxvxvbcvbcvb

//kjhgf

}

}